name: shinbun
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  very_good_analysis: ^4.0.0+1


flutter:
  uses-material-design: true

import_sorter:
  comments: false
